<div class="navbar">
    <div class="dropdown">
        <button class="dropbtn">🔐</button>
        <div class="dropdown-content">
            <a href="<?= CONF_URL_BASE ?>">Home</a>
            <a href="<?= CONF_URL_BASE . '/login' ?>">Entrar</a>
            <a href="<?= CONF_URL_BASE . '/register'?>">Cadastrar</a>
        </div>
    </div>
</div>
<div class="parent-container">
    <div class="login-box">
        <h2>LOGIN</h2>
        <form action="/login" method="post">
            <div class="user-box">
                <input type="text" name="username" required>
                <label>Usuário</label>
            </div>
            <div class="user-box">
                <input type="password" name="password" required>
                <label>Senha</label>
            </div>
            <button type="submit">Entrar</button>
        </form>
    </div>
</div>

