<div class="parent-container">
    <div class="login-box">
        <h2>LOGIN</h2>
        <form action="<?= CONF_URL_BASE ?>/login" method="post">
            <div class="user-box">
                <input type="text" name="username" required>
                <label>Usuário</label>
            </div>
            <div class="user-box">
                <input type="password" name="password" required>
                <label>Senha</label>
            </div>
            <button type="submit">Entrar</button>
        </form>
    </div>
</div>

