<div class="parent-container">
    <div class="login-box">
        <h2>REGISTER</h2>
        <form action="#">
            <div class="user-box">
                <input type="text" id="nome" name="nome" required>
                <label for="nome">Nome</label>
            </div>
            <div class="user-box">
                <input type="email" id="email" name="email" required>
                <label for="email">Email</label>
            </div>
            <div class="user-box">
                <input type="password" id="senha" name="senha" required>
                <label for="senha">Senha</label>
            </div>
            <div class="address-row">
                <div class="user-box">
                    <input type="text" id="rua" name="rua" required>
                    <label for="rua">Rua</label>
                </div>
                <div class="user-box">
                    <input type="text" id="numero" name="numero" required>
                    <label for="numero">Número</label>
                </div>
            </div>
            <div class="address-row">
                <div class="user-box">
                    <input type="text" id="bairro" name="bairro" required>
                    <label for="bairro">Bairro</label>
                </div>
                <div class="user-box">
                    <input type="text" id="cidade" name="cidade" required>
                    <label for="cidade">Cidade</label>
                </div>
            </div>
            <div class="address-row">
                <div class="user-box">
                    <input type="text" id="estado" name="estado" required>
                    <label for="estado">Estado</label>
                </div>
                <div class="user-box">
                    <input type="text" id="cep" name="cep" required>
                    <label for="cep">CEP</label>
                </div>
            </div>
            <button type="submit">Cadastrar</button>
        </form>
    </div>
</div>